### PR TITLE
Encode database authentication information for issue with special characters

### PR DESCRIPTION
**Pull request by KeonHee**
Relate to: 
- https://github.com/apache/incubator-openwhisk-package-alarms/pull/115
- https://github.com/apache/incubator-openwhisk-package-alarms/pull/121

The last PR did not work in couchdb either(Sorry...!). So I found a new method, and I am using it in my in-house paas. I hope that cloudant will also work.

I adjusted the database settings of the provider and package to the same, and modified the deployment script.

### CODE REVIEW

**Review by jasonpet — CHANGES_REQUESTED** [review]
Removing support for the DB_URL param would break existing API.  Please rework to support existing param or new params (so either way would work).  Other option would be to take the  DB_URL param and parse out the username and password to encode.

**Comment by KeonHee** [comment]
@jasonpet 
I modified the existing API to use it as it is :)

**Comment by KeonHee** [comment]
@jasonpet 
I modified it to use an existing url and add only username and password.

**Comment by dgrove-oss** [comment]
@jasonpet - should this be closed as stale?

**Comment by style95** [comment]
Can we include this change?

**Review by style95 — APPROVED** [review]
LGTM

**Comment by KeonHee** [comment]
Like https://github.com/apache/openwhisk-package-alarms/pull/155#pullrequestreview-141367905, I have modified to use the existing DB_URL. And this change still works well.

**Comment by rabbah** [comment]
LGTM - I've been working with the alarm package recently and can try this out.

**Review by rabbah — APPROVED** [review]
Changes look good to me.

**Comment by style95** [comment]
It seems I cannot merge this PR because @jasonpet requested changes.
@jasonpet Do you still have any comments on this?

**Comment by rabbah** [comment]
I think the changes made address the requested change and we can unblock the PR but I'll ping Jason on Slack as a courtesy.

**Review by jasonpet — APPROVED** [review]

**Comment by rabbah** [comment]
Thanks @jasonpet.

**Pull request merged**
